name: Build Wheels

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:  # 允许手动触发

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu,x86_64-pc-windows-msvc,x86_64-apple-darwin

      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install openssl@3
          echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.16.2

      - name: Show Python version
        run: |
          python --version
          python -c "import sys; print(sys.executable)"

      - name: Show Rust version
        run: |
          rustc --version
          cargo --version

      - name: Build wheels
        env:
          CIBW_BEFORE_BUILD: |
            pip install maturin
            echo "Current directory: $(pwd)"
            echo "Directory contents:"
            ls -la
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "pp* *-musllinux* *-manylinux_i686*"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_MACOS: "arm64 x86_64"
          CIBW_VERBOSE: 2
          CIBW_TEST_COMMAND: >
            python -c "import bomiot_check; print('Import successful')"
          # macOS specific environment variables
          CIBW_ENVIRONMENT_MACOS: >
            OPENSSL_DIR=/opt/homebrew/opt/openssl@3
            OPENSSL_INCLUDE_DIR=/opt/homebrew/opt/openssl@3/include
            OPENSSL_LIB_DIR=/opt/homebrew/opt/openssl@3/lib
            RUSTFLAGS="-C target-feature=+crt-static"
          # Build command for macOS
          CIBW_BEFORE_BUILD_MACOS: |
            pip install maturin
            export OPENSSL_DIR=/opt/homebrew/opt/openssl@3
            export OPENSSL_INCLUDE_DIR=/opt/homebrew/opt/openssl@3/include
            export OPENSSL_LIB_DIR=/opt/homebrew/opt/openssl@3/lib
            export RUSTFLAGS="-C target-feature=+crt-static"
            echo "OpenSSL environment variables:"
            env | grep OPENSSL
            echo "RUSTFLAGS: $RUSTFLAGS"
          CIBW_BUILD_COMMAND: |
            echo "Starting build..."
            echo "Current directory: $(pwd)"
            echo "Directory contents:"
            ls -la
            maturin build --release --strip --manylinux off --out wheelhouse --verbose
            echo "Build completed with status: $?"
            ls -la wheelhouse/
          CIBW_BUILD_FRONTEND: "pip"
          CIBW_BUILD_FRONTEND_ARGS: "--no-deps"
          CIBW_BUILD_VERBOSITY: 3
          CIBW_MACOS_DEPLOYMENT_TARGET: "10.9"
        run: |
          python -m cibuildwheel --output-dir wheelhouse
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            dir wheelhouse
          else
            ls -la wheelhouse/
          fi
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          if-no-files-found: error 