name: Build universal abi3 wheels for Python 3.9+ on Windows, macOS, Linux

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build_abi3_wheels:
    name: Build abi3 wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # 1. 检出仓库代码
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install OpenSSL and dependencies
        if: runner.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
          echo "OPENSSL_DIR=/usr" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          echo "OPENSSL_NO_VENDOR=1" >> $GITHUB_ENV
          echo "PYO3_STATIC_LIB=1" >> $GITHUB_ENV

      - name: Install vcpkg & OpenSSL
        if: runner.os == 'windows'
        run: |
          git clone https://github.com/Microsoft/vcpkg C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
          C:\vcpkg\vcpkg.exe install openssl:x64-windows
      
      - name: Set env vars
        if: runner.os == 'windows'
        run: |
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV
          echo "OPENSSL_DIR=C:\vcpkg\installed\x64-windows" >> $env:GITHUB_ENV
          echo "OPENSSL_NO_VENDOR=1" >> $env:GITHUB_ENV
      
      # 2. 安装 Rust 工具链
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # 3. 安装 Python 3.9（abi3 轮子最低要求）
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # 4. 升级 pip 并安装 build dependencies
      - name: Upgrade pip and install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install maturin build

      # 5. 使用 maturin 构建 abi3 wheel
      - name: Build wheel
        run: |
          python -m maturin build --release --interpreter python3.9 --target-dir dist

      # 6. 上传 wheel 产物
      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: abi3-wheels-${{ runner.os }}
          path: dist/*.whl

      # 7. 可选：构建并上传 sdist
      - name: Build sdist
        run: |
          python -m build --sdist --outdir dist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist-${{ runner.os }}
          path: dist/*.tar.gz
